<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "subscriptions"
 *
 * Auto generated by Extension Builder 2018-03-01
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Email-Subscriptions',
	'description' => 'E-mail Subscriptions',
	'category' => 'plugin',
	'author' => '',
	'author_email' => '',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '8.7.4-8.9.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);