<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "tp3_jobs"
 *
 * Auto generated by Extension Builder 2018-02-17
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'tp3 Jobs',
    'description' => 'Joboffer on tp3',
    'category' => 'fe',
    'author' => 'Thomas Ruta',
    'author_email' => 'email@thomasruta.de',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '0.1.5',
    'author_company' => 'tp3',
    'constraints' =>
        array (
            'depends' =>
                array (
                    'typo3' => '8.7.0-9.0.99',
                ),
            'conflicts' =>
                array (

                ),
            'suggests' =>
                array (
                ),
        ),
    'autoload' =>
        array (
            'psr-4' =>
                array (
                    'Tp3\\Tp3Jobs\\' => 'Classes',
                ),
        ),

];

