# This is the project specific Settings.yml file.
# Place Sphinx specific build information here.
# Settings given here will replace the settings of 'conf.py'.

# Below is an example of intersphinx mapping declaration
# Add more mappings depending on what manual you want to link to
# Remove entirely if you don't need cross-linking

---
conf.py:
  copyright: 2018
  project: tp3 Jobs (Deutsch)
  version: 0.1
  release: 0.1.4
  latex_documents:
  - - Index
    - tp3_jobs.tex
    - tp3 Jobs
    - Thomas Ruta
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage[typo3]
  html_theme_options:
    github_repository: https://github.com/webtp3/tp3_jobs
    github_branch: latest
  intersphinx_mapping:
    t3tsref:
    - http://docs.typo3.org/typo3cms/TyposcriptReference/
    - null

...
