<?php

// autoload_classmap.php @generated by TYPO3

$typo3InstallDir = PATH_site;

return array(
    'BK2K\\BootstrapPackage\\Composer\\ChangelogScript' => $typo3InstallDir . 'typo3conf/ext/bootstrap_package/Classes/Composer/ChangelogScript.php',
    'BK2K\\BootstrapPackage\\Composer\\VersionScript' => $typo3InstallDir . 'typo3conf/ext/bootstrap_package/Classes/Composer/VersionScript.php',
    'BK2K\\BootstrapPackage\\DataProcessing\\FlexFormProcessor' => $typo3InstallDir . 'typo3conf/ext/bootstrap_package/Classes/DataProcessing/FlexFormProcessor.php',
    'BK2K\\BootstrapPackage\\DataProcessing\\MenuProcessor' => $typo3InstallDir . 'typo3conf/ext/bootstrap_package/Classes/DataProcessing/MenuProcessor.php',
    'BK2K\\BootstrapPackage\\Hooks\\PageRenderer\\PreProcessHook' => $typo3InstallDir . 'typo3conf/ext/bootstrap_package/Classes/Hooks/PageRenderer/PreProcessHook.php',
    'BK2K\\BootstrapPackage\\Hooks\\TceMain\\ClearCacheHook' => $typo3InstallDir . 'typo3conf/ext/bootstrap_package/Classes/Hooks/TceMain/ClearCacheHook.php',
    'BK2K\\BootstrapPackage\\Service\\CompileService' => $typo3InstallDir . 'typo3conf/ext/bootstrap_package/Classes/Service/CompileService.php',
    'BK2K\\BootstrapPackage\\Service\\InstallService' => $typo3InstallDir . 'typo3conf/ext/bootstrap_package/Classes/Service/InstallService.php',
    'BK2K\\BootstrapPackage\\Updates\\AccordionContentElementUpdate' => $typo3InstallDir . 'typo3conf/ext/bootstrap_package/Classes/Updates/AccordionContentElementUpdate.php',
    'BK2K\\BootstrapPackage\\Updates\\BulletContentElementUpdate' => $typo3InstallDir . 'typo3conf/ext/bootstrap_package/Classes/Updates/BulletContentElementUpdate.php',
    'BK2K\\BootstrapPackage\\Updates\\CarouselContentElementUpdate' => $typo3InstallDir . 'typo3conf/ext/bootstrap_package/Classes/Updates/CarouselContentElementUpdate.php',
    'BK2K\\BootstrapPackage\\Updates\\ExternalMediaContentElement' => $typo3InstallDir . 'typo3conf/ext/bootstrap_package/Classes/Updates/ExternalMediaContentElement.php',
    'BK2K\\BootstrapPackage\\Updates\\ListGroupContentElement' => $typo3InstallDir . 'typo3conf/ext/bootstrap_package/Classes/Updates/ListGroupContentElement.php',
    'BK2K\\BootstrapPackage\\Updates\\PanelContentElementUpdate' => $typo3InstallDir . 'typo3conf/ext/bootstrap_package/Classes/Updates/PanelContentElementUpdate.php',
    'BK2K\\BootstrapPackage\\Updates\\SectionFrameToFrameClassUpdate' => $typo3InstallDir . 'typo3conf/ext/bootstrap_package/Classes/Updates/SectionFrameToFrameClassUpdate.php',
    'BK2K\\BootstrapPackage\\Updates\\TabContentElementUpdate' => $typo3InstallDir . 'typo3conf/ext/bootstrap_package/Classes/Updates/TabContentElementUpdate.php',
    'BK2K\\BootstrapPackage\\Updates\\TableContentElementUpdate' => $typo3InstallDir . 'typo3conf/ext/bootstrap_package/Classes/Updates/TableContentElementUpdate.php',
    'BK2K\\BootstrapPackage\\Updates\\TexticonContentElement' => $typo3InstallDir . 'typo3conf/ext/bootstrap_package/Classes/Updates/TexticonContentElement.php',
    'BK2K\\BootstrapPackage\\Utility\\ExternalMediaUtility' => $typo3InstallDir . 'typo3conf/ext/bootstrap_package/Classes/Utility/ExternalMediaUtility.php',
    'BK2K\\BootstrapPackage\\Utility\\TextIconUtility' => $typo3InstallDir . 'typo3conf/ext/bootstrap_package/Classes/Utility/TextIconUtility.php',
    'BK2K\\BootstrapPackage\\ViewHelpers\\DataRelationViewHelper' => $typo3InstallDir . 'typo3conf/ext/bootstrap_package/Classes/ViewHelpers/DataRelationViewHelper.php',
    'BK2K\\BootstrapPackage\\ViewHelpers\\ExplodeViewHelper' => $typo3InstallDir . 'typo3conf/ext/bootstrap_package/Classes/ViewHelpers/ExplodeViewHelper.php',
    'BK2K\\BootstrapPackage\\ViewHelpers\\ExternalMediaViewHelper' => $typo3InstallDir . 'typo3conf/ext/bootstrap_package/Classes/ViewHelpers/ExternalMediaViewHelper.php',
    'BK2K\\BootstrapPackage\\ViewHelpers\\FalViewHelper' => $typo3InstallDir . 'typo3conf/ext/bootstrap_package/Classes/ViewHelpers/FalViewHelper.php',
    'BK2K\\BootstrapPackage\\ViewHelpers\\LastImageInfoViewHelper' => $typo3InstallDir . 'typo3conf/ext/bootstrap_package/Classes/ViewHelpers/LastImageInfoViewHelper.php',
);
