<?php

// autoload_classmap.php @generated by TYPO3

$typo3InstallDir = PATH_site;

return array(
    'Contact\\Contact\\Controller\\ListController' => $typo3InstallDir . 'typo3conf/ext/contact/Classes/Controller/ListController.php',
    'Contact\\Contact\\Domain\\Model\\List' => $typo3InstallDir . 'typo3conf/ext/contact/Classes/Domain/Model/List.php',
    'Helhum\\UploadExample\\Controller\\ExampleController' => $typo3InstallDir . 'typo3conf/ext/upload_example/Classes/Controller/ExampleController.php',
    'Helhum\\UploadExample\\Domain\\Model\\Example' => $typo3InstallDir . 'typo3conf/ext/upload_example/Classes/Domain/Model/Example.php',
    'Helhum\\UploadExample\\Domain\\Model\\FileReference' => $typo3InstallDir . 'typo3conf/ext/upload_example/Classes/Domain/Model/FileReference.php',
    'Helhum\\UploadExample\\Domain\\Repository\\ExampleRepository' => $typo3InstallDir . 'typo3conf/ext/upload_example/Classes/Domain/Repository/ExampleRepository.php',
    'Helhum\\UploadExample\\Property\\TypeConverter\\ObjectStorageConverter' => $typo3InstallDir . 'typo3conf/ext/upload_example/Classes/Property/TypeConverter/ObjectStorageConverter.php',
    'Helhum\\UploadExample\\Property\\TypeConverter\\UploadedFileReferenceConverter' => $typo3InstallDir . 'typo3conf/ext/upload_example/Classes/Property/TypeConverter/UploadedFileReferenceConverter.php',
    'Helhum\\UploadExample\\ViewHelpers\\Form\\UploadViewHelper' => $typo3InstallDir . 'typo3conf/ext/upload_example/Classes/ViewHelpers/Form/UploadViewHelper.php',
    'Job\\JobAreas\\Controller\\JobController' => $typo3InstallDir . 'typo3conf/ext/job_areas/Classes/Controller/JobController.php',
    'Subscriptions\\Subscriptions\\Controller\\ListController' => $typo3InstallDir . 'typo3conf/ext/subscriptions/Classes/Controller/ListController.php',
    'Subscriptions\\Subscriptions\\Domain\\Model\\List' => $typo3InstallDir . 'typo3conf/ext/subscriptions/Classes/Domain/Model/List.php',
    'Subscriptions\\Subscriptions\\Domain\\Repository\\ListRepository' => $typo3InstallDir . 'typo3conf/ext/subscriptions/Classes/Domain/Repository/ListRepository.php',
);
